# Generated by Django 5.0.4 on 2024-04-30 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город, в котором предоставляется услуга проведения спортивного мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Types_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип спортивного мероприятия')),
                ('price', models.FloatField(verbose_name='Минимальная стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проведения спортивного мероприятия')),
                ('description', models.CharField(max_length=255, verbose_name='Описание спортивного мероприятия')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оформления заказа на проведение спортивного мероприятия')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время проведения спортивного мероприятия')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время окончания спортивного мероприятия')),
                ('budget', models.FloatField(verbose_name='Бюджет организатора')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.citys')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.types_events')),
            ],
        ),
    ]
