# Generated by Django 5.0.4 on 2024-04-30 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citys',
            options={'verbose_name': 'Города предоставления услуг', 'verbose_name_plural': 'Города предоставления услуг'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Спортивные мероприятия', 'verbose_name_plural': 'Спортивные мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='types_events',
            options={'verbose_name': 'Типы спортивных мероприятий', 'verbose_name_plural': 'Типы спортивных мероприятий'},
        ),
        migrations.AlterField(
            model_name='events',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.citys', verbose_name='Город проведения спортивного мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.types_events', verbose_name='Тип спортивного мероприятия'),
        ),
    ]
