# Generated by Django 5.0.4 on 2024-04-30 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_citys_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_order',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 1, 1, 38, 9, 861359), verbose_name='Дата и время оформления заказа на проведение спортивного мероприятия'),
        ),
    ]
